### ISSUE TITLE
Assertion error in Case 1 on master

### ISSUE THREAD

**Issue by keeganryan** [AGFeldman/jaka#29]
When I run case1.json on master, it runs fine for a while, but crashes at ~700s

input:
python run.py cases/case1.json

output:
[...]
Time 756.60635947 : F1 received ack for (476, H2, H1, ack)
Traceback (most recent call last):
  File "run.py", line 39, in <module>
    simulate(network)
  File "run.py", line 16, in simulate
    globals_.event_manager.run()
  File "/CS143/jaka/event_manager.py", line 59, in run
    scheduled_action()
  File "/CS143/jaka/link.py", line 108, in packet_reaches_endpoint
    dst_endpoint.device.receive_packet(packet)
  File "/CS143/jaka/host.py", line 17, in receive_packet
    packet.flow.receive_ack(packet)
  File "/CS143/jaka/flow.py", line 96, in receive_ack
    assert packet.id_ in self.packets_waiting_for_acks
AssertionError

**Comment by AGFeldman** [comment]
Fixed with https://github.com/AGFeldman/jaka/pull/28
